FROM python:3.12-bullseye

RUN apt-get update && apt-get install -y

RUN mkdir -p /python_django
WORKDIR /python_django

COPY ./requirements.txt /python_django/requirements.txt
RUN pip install --upgrade pip && pip install -r /python_django/requirements.txt

RUN pip install pylint==2.16.2 sqlfluff==1.4.5 parameterized==0.9.0 pycodestyle==2.10.0 snapshottest==0.6.0 coverage==7.2.7 ipython==8.24.0 pylint-django==2.5.5

ENTRYPOINT ["bash"]